name: 'MergeSafe Scanner'
description: 'Run MergeSafe scanner and optional engines (Semgrep, Gitleaks)'
inputs:
  path:
    description: 'Path to scan (relative to repo root)'
    required: false
    default: '.'
  mode:
    description: 'Scan mode'
    required: false
    default: 'fast'
  fail_on:
    description: 'Fail threshold'
    required: false
    default: 'high'
  engines:
    description: 'Comma-separated engines list (e.g. mergesafe,semgrep,gitleaks)'
    required: false
    default: 'mergesafe,semgrep,gitleaks'
  out_dir:
    description: 'Output directory (relative to repo root)'
    required: false
    default: 'mergesafe'
  upload_sarif:
    description: 'Upload SARIF to GitHub Code Scanning'
    required: false
    default: 'true'
  comment_pr:
    description: 'Comment PR summary'
    required: false
    default: 'true'
  config:
    description: 'Optional config file path (relative to repo root)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable pnpm (corepack)
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@10.0.0 --activate
        pnpm -v

    - uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/mergesafe-tools
        key: mergesafe-tools-${{ runner.os }}-${{ runner.arch }}

    - name: Install MergeSafe dependencies
      shell: bash
      working-directory: ${{ github.action_path }}/../..
      run: pnpm install --frozen-lockfile

    - name: Run MergeSafe scan (scans USER repo)
      shell: bash
      working-directory: ${{ github.action_path }}/../..
      env:
        MERGESAFE_TOOLS_DIR: ${{ runner.temp }}/mergesafe-tools
      run: |
        SCAN_PATH="${GITHUB_WORKSPACE}/${{ inputs.path }}"
        OUT_DIR="${GITHUB_WORKSPACE}/${{ inputs.out_dir }}"
        CONFIG_ARG=""
        if [ -n "${{ inputs.config }}" ]; then
          CONFIG_ARG="--config ${GITHUB_WORKSPACE}/${{ inputs.config }}"
        fi

        echo "MERGESAFE_OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

        pnpm -C packages/cli dev -- scan "$SCAN_PATH" \
          --mode "${{ inputs.mode }}" \
          --fail-on "${{ inputs.fail_on }}" \
          --engines "${{ inputs.engines }}" \
          --out-dir "$OUT_DIR" \
          --format "json,html,sarif,md" \
          $CONFIG_ARG

    - name: Upload SARIF
      if: ${{ inputs.upload_sarif == 'true' }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ env.MERGESAFE_OUT_DIR }}/results.sarif

    - name: Comment PR summary
      if: ${{ inputs.comment_pr == 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const outDir = process.env.MERGESAFE_OUT_DIR;
          const body = fs.readFileSync(path.join(outDir, 'summary.md'), 'utf8');
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body,
          });
