name: 'MergeSafe Scanner'
description: 'Run MergeSafe scanner with default engines (mergesafe, semgrep, gitleaks, cisco, osv) or a custom engines list'
inputs:
  path:
    description: 'Path to scan (relative to repo root)'
    required: false
    default: '.'
  mode:
    description: 'Scan mode (standard or fast)'
    required: false
    default: 'standard'
  fail_on:
    description: 'Fail threshold'
    required: false
    default: 'high'
  engines:
    description: 'Optional engines list (comma-separated or all); defaults to mergesafe,semgrep,gitleaks,cisco,osv when omitted. Use all to include optional engines like trivy.'
    required: false
    default: ''
  out_dir:
    description: 'Output directory (relative to repo root)'
    required: false
    default: 'mergesafe'
  upload_sarif:
    description: 'Upload SARIF to GitHub Code Scanning'
    required: false
    default: 'true'
  comment_pr:
    description: 'Comment PR summary'
    required: false
    default: 'false'
  config:
    description: 'Optional config file path (relative to repo root)'
    required: false
    default: ''
  verify_downloads:
    description: 'Downloaded binary verification mode: off, warn, or strict'
    required: false
    default: 'strict'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable pnpm (corepack)
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@10.0.0 --activate
        pnpm -v

    - uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/mergesafe-tools
        key: mergesafe-tools-${{ runner.os }}-${{ runner.arch }}

    - name: Install MergeSafe dependencies
      shell: bash
      working-directory: ${{ github.action_path }}/../..
      run: pnpm install --frozen-lockfile

    - name: Run MergeSafe scan (scans USER repo)
      shell: bash
      working-directory: ${{ github.action_path }}/../..
      env:
        MERGESAFE_TOOLS_DIR: ${{ runner.temp }}/mergesafe-tools
      run: |
        SCAN_PATH="${GITHUB_WORKSPACE}/${{ inputs.path }}"
        OUT_DIR="${GITHUB_WORKSPACE}/${{ inputs.out_dir }}"
        CONFIG_ARG=""
        ENGINES_ARG=""
        if [ -n "${{ inputs.config }}" ]; then
          CONFIG_ARG="--config ${GITHUB_WORKSPACE}/${{ inputs.config }}"
        fi
        if [ -n "${{ inputs.engines }}" ]; then
          ENGINES_ARG="--engines ${{ inputs.engines }}"
        fi

        echo "MERGESAFE_OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

        pnpm -C packages/cli dev -- scan "$SCAN_PATH" \
          --mode "${{ inputs.mode }}" \
          --fail-on "${{ inputs.fail_on }}" \
          --out-dir "$OUT_DIR" \
          --format "json,html,sarif,md" \
          --verify-downloads "${{ inputs.verify_downloads }}" \
          $ENGINES_ARG \
          $CONFIG_ARG

    - name: Check MergeSafe outputs
      id: outputs
      shell: bash
      run: |
        OUT_DIR="${MERGESAFE_OUT_DIR:-${GITHUB_WORKSPACE}/${{ inputs.out_dir }}}"
        echo "out_dir=$OUT_DIR" >> "$GITHUB_OUTPUT"
        [ -f "$OUT_DIR/results.sarif" ] && echo "has_sarif=true" >> "$GITHUB_OUTPUT" || echo "has_sarif=false" >> "$GITHUB_OUTPUT"
        [ -f "$OUT_DIR/summary.md" ] && echo "has_summary=true" >> "$GITHUB_OUTPUT" || echo "has_summary=false" >> "$GITHUB_OUTPUT"

    - name: Upload SARIF
      if: ${{ inputs.upload_sarif == 'true' && steps.outputs.outputs.has_sarif == 'true' }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.outputs.outputs.out_dir }}/results.sarif

    - name: Comment PR summary
      if: ${{ inputs.comment_pr == 'true' && github.event_name == 'pull_request' && steps.outputs.outputs.has_summary == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const outDir = process.env.MERGESAFE_OUT_DIR;
          const body = fs.readFileSync(path.join(outDir, 'summary.md'), 'utf8');
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body,
          });
